title: Joonas' Portfolio
description: Personal portfolio website showcasing my projects and skills
author: Joonas Sulkakoski
email: your.email@example.com
url: "https://DylaniestDylan.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Exclude files from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock